<a href="https://colab.research.google.com/github/BadMojo123/ML/blob/main/TfCertification/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#start!

In [3]:
import tensorflow as tf
import numpy as np
print(tf.__version__)



2.8.2


In [4]:
scalar = tf.constant(7)
scalar
scalar.ndim

0

In [5]:
vector1 = tf.constant([12,14])
vector1
vector1.ndim

1

In [6]:
matrix1 = tf.constant([[1,43],[34,65]])
matrix1
matrix1.ndim


2

In [7]:
matrix2 = tf.constant([[1,2,3],[5,6,7]],dtype=tf.float16)
matrix2
matrix2.ndim

2

In [8]:
# tensor = tf.constant()

In [9]:
var1 = tf.Variable([11,14])
var1[0].assign(1123)
var1

# vector1[0].assign(121)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1123,   14], dtype=int32)>

In [10]:
randGenerator = tf.random.Generator.from_seed(22)
print(randGenerator)
rand = randGenerator.normal(shape=(3,6))
print(rand)
rand2 = randGenerator.uniform(shape=(3,6))
print(rand2)
print(rand == rand2)


tf.Tensor(
[[-0.7531523   2.0261486  -0.06997604  0.85445154  0.1175475   0.03493892]
 [-1.5700307   0.4457582   0.10944034 -0.8035768  -1.7166729   0.3738578 ]
 [-0.14371012 -0.34646833  1.1456194  -0.416       0.43369916  1.0241015 ]], shape=(3, 6), dtype=float32)
tf.Tensor(
[[0.50262177 0.7719592  0.2117778  0.01571906 0.02157342 0.4694276 ]
 [0.76560867 0.8094878  0.9408673  0.7096205  0.49367034 0.812148  ]
 [0.7664677  0.14390814 0.63637483 0.24003983 0.16539216 0.45334506]], shape=(3, 6), dtype=float32)
tf.Tensor(
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]], shape=(3, 6), dtype=bool)


In [11]:
print(tf.random.shuffle(rand))


tf.Tensor(
[[-0.7531523   2.0261486  -0.06997604  0.85445154  0.1175475   0.03493892]
 [-1.5700307   0.4457582   0.10944034 -0.8035768  -1.7166729   0.3738578 ]
 [-0.14371012 -0.34646833  1.1456194  -0.416       0.43369916  1.0241015 ]], shape=(3, 6), dtype=float32)


In [12]:
tf.random.set_seed(22)
print(tf.random.shuffle(rand,seed=33))


tf.Tensor(
[[-1.5700307   0.4457582   0.10944034 -0.8035768  -1.7166729   0.3738578 ]
 [-0.14371012 -0.34646833  1.1456194  -0.416       0.43369916  1.0241015 ]
 [-0.7531523   2.0261486  -0.06997604  0.85445154  0.1175475   0.03493892]], shape=(3, 6), dtype=float32)


In [13]:
tf.zeros((10,3),dtype=tf.float16)

<tf.Tensor: shape=(10, 3), dtype=float16, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)>

In [14]:
vector_a = np.arange(0,22,dtype=np.float16)
vector_a

tensorFromNumpy = tf.constant(vector_a, shape=(2,11))
print(tensorFromNumpy)
tensorFromNumpy.ndim


tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]], shape=(2, 11), dtype=float16)


2

In [15]:
Rank4Tensor = randGenerator.normal(shape=(2,3,4,5))
Rank4Tensor.ndim
print(f'Size of tensor{tf.size(Rank4Tensor)}')

Rank4Tensor[:,:,:,1]



Size of tensor120


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.5686429 ,  0.06753699,  0.10600277,  0.51010656],
        [-0.7156006 ,  0.6539492 ,  0.67621213, -2.3856606 ],
        [-0.34048697, -0.22617333,  0.63893604, -0.9314237 ]],

       [[-2.0068674 , -0.86546683,  1.1681029 , -1.5956855 ],
        [ 0.5900225 ,  0.50609887,  1.6251978 ,  0.4898146 ],
        [-1.4549799 ,  1.6851732 ,  1.5699317 , -0.2931341 ]]],
      dtype=float32)>

In [16]:
tensor = tf.constant([[1,2,3],[13,14,15],[21,22,23]], dtype=tf.float16)
tensor2 = tf.constant([[1,2,3],[13,14,15]], dtype=tf.float16)
tensor2 = tf.reshape(tensor2,shape=(3,2))
print(tensor)
# print(tensor * tensor2)
print(tensor @ tensor2)
print(tf.matmul(tensor,tensor2))
new = tf.matmul(tensor,tensor2)

tensor2 = tf.transpose(tensor2)
print(tensor2)
tensor2 = tf.pow(tensor2,-1)
print(tensor2)
result = tf.matmul(new,tensor2)
print(result)

# matmulTest = tf.matmul(tensor,tensor)
# matmulTest

tf.Tensor(
[[ 1.  2.  3.]
 [13. 14. 15.]
 [21. 22. 23.]], shape=(3, 3), dtype=float16)
tf.Tensor(
[[ 49.  73.]
 [265. 433.]
 [409. 673.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[ 49.  73.]
 [265. 433.]
 [409. 673.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[ 1.  3. 14.]
 [ 2. 13. 15.]], shape=(2, 3), dtype=float16)
tf.Tensor(
[[1.      0.3333  0.0714 ]
 [0.5     0.0769  0.06665]], shape=(2, 3), dtype=float16)
tf.Tensor(
[[ 85.5   21.94   8.37]
 [481.5  121.6   47.78]
 [745.5  188.    74.06]], shape=(3, 3), dtype=float16)


In [17]:
X = tf.constant([[1,2],
            [3,4],
            [5,6]])

Y = tf.constant([[11,12],
            [23,24],
            [35,36]])

print(f'reshape: \n {tf.matmul(X,tf.reshape(Y,shape=(2,3)))}' )
print(f'transpose: \n {tf.matmul(X,tf.transpose(Y))}' )

print(f'transpose: \n {tf.tensordot(X,tf.transpose(Y),axes=2)}' )



reshape: 
 [[ 59  82  95]
 [129 176 213]
 [199 270 331]]
transpose: 
 [[ 35  71 107]
 [ 81 165 249]
 [127 259 391]]
transpose: 
 546


In [18]:
C = tf.constant([[100,2,4],[6,4,100]])
C.dtype

# D = tf.cast(C,dtype=tf.dtypes.float16)
# D.dtype

# print(tf.argmax(C,axis=0))
A = tf.argmax(C,axis=1)
print(A)




tf.Tensor([0 2], shape=(2,), dtype=int64)


In [19]:
listA = [4,2,2]
OHE = tf.one_hot(listA,depth = 6)

print(OHE)

tf.Tensor(
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]], shape=(3, 6), dtype=float32)


In [22]:
sqrt = tf.constant(1/2)

print(tf.pow(2.,0.5))

tf.Tensor(1.4142135, shape=(), dtype=float32)
